name = "FloatingError"
uuid = "5d056e38-7323-42c3-ac3e-20e2b8377681"
authors = ["Xuanzhao Gao <gaoxuanzhao@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
